modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Nekeras/borderless/issues"

[[mods]]
    modId="borderless"
    version="${version}"
    displayName="Borderless Window"
    displayURL="https://nekeras.de/projects/borderless"
    authors="Nekeras"
    description='''
    Enables the fullscreen mode 'Borderless Window', which replaces the standard Minecraft fullscreen. This allows to easily switch monitors when Minecraft is not focussed, without minimizing the game.
    '''
